title: some nlp kid's website
email: <first name, no hyphen> (at) cs.columbia.edu
description: Fei-Tzin's website.
twitter_username: feitzin
github_username: feitzin
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-173100957-1      # Required - replace with your tracking id
    anonymizeIp: true       # Optional - Default: false - set to true for anonymized tracking
plugins:
  - jekyll-redirect-from
  - jekyll-analytics